# Test your FastAPI endpoints

GET http://127.0.0.1:80/
Accept: application/json

###

POST http://127.0.0.1:80/customers/
Content-Type: application/json

{
  "name": "xyz",
  "email": "xyz@mail.com"
}
###
